version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: ssafy/teongbin
    container_name: teongbin
    ports:
      - "8080:8080"
    env_file:
      - .env.backend  # Spring Boot용 환경 파일

  dashboard:
    build:
      context: ./frontend/dashboard
    image: ssafy/dashboard
    container_name: dashboard
    ports:
      - "8083:80"
    env_file:
      - .env  # Vue.js + Vite용 환경 파일

  product_page:
    build:
      context: ./frontend/product-page
    image: ssafy/product_page
    container_name: product_page
    ports:
      - "8082:80"
